name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: dsdeliver

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: lucianobrum
          password: ${{ secrets.PWD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lucianobrum/dsdeliver:${{github.sha}}