#file: noinspection YAMLSchemaValidation
name: ds-deliver

on:
  push:
    branches: [ "main", "CI/CD" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -DskipTests -P prod

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: lucianobrum
          password: ${{ secrets.PWD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lucianobrum/dsdeliver:${{github.sha}}