#file: noinspection YAMLSchemaValidation
name: ds-deliver

on:
  push:
    branches: [ "main", "CI/CD" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -DskipTests -P prod

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: dsdeliver
          # A file, directory or wildcard pattern that describes what to upload
          path: main
          # The desired behavior if no files are found using the provided path.

  docker:
    needs: build
    uses: ./.github/workflows/build-and-publish-image.yml
    secrets: inherit